spring:
  profiles:
    active: qa
  datasource:
    url: jdbc:mysql://skysrd.iptime.org:3306/modyeo
    hikari:
      username: api
      password: modyeo!@
      driver-class-name: com.mysql.cj.jdbc.Driver

  jwt:
    secret: Z2VvLWdhdGhlcmluZy1zeXN0ZW0tbW9keWVvLWFwaS1zZXJ2ZXItc3ByaW5nLWJvb3QtanBhLWp3dC1zcHJpbmctc2VjdXJpdHktd2lydHRlci1hbmpvbmdnaWwtamFuZ21pbnNlb2stMjAyMi0wNi0wOQo=

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
#        format_sql: true
#        use_sql_comments: true
#        show_sql: true
    open-in-view: false

  redis:
    host: skysrd.iptime.org
    port: 6379

logging:
  level:
#    org.hibernate.sql: debug


profiles:
  active: qa